### ISSUE TITLE
Balance is so wack

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#107]
Nothing makes sense.
Fire wizard is all stupid
Alchemist is dumb
Assassin has nothing
Paladin has even less
Some items are in middle, some on left

**Comment by Tman2143** [comment]
Assassin has flash nade
Paladin has low cooldown hammer throw for space closing but disabled hammer during throw

**Comment by Tman2143** [comment]
Fire mage has speed boost with damage boost

**Comment by Tman2143** [comment]
Fire mage wall bigger

**Comment by Bobthe28th** [comment]
I will try to make firewall bigger, but say it is 3 blocks wide does that mean it shoots out 3 fire walls or one firewall that also has fire to its left and right @Tman2143
