### ISSUE TITLE
How will the archer select their arrows

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#34]
The archer has multiple arrows to choose from, how should they select between them?

**Comment by Bobthe28th** [comment]
Switching hotbar slots around WILL result in some issues

**Comment by Bobthe28th** [comment]
Will prob need to make new CTFItem that is an array that extends from CTFBuildupItem

**Comment by Bobthe28th** [comment]
I was thinking before that the player should just press the number the arrow corresponds to in the hotbar and that puts the arrow in their offhand but idk

**Comment by Bobthe28th** [comment]
Or scroll wheel cycles through them?

**Comment by Tman2143** [comment]
every arrow is an arrow until you hold right click then it's a bow and you shoot

**Comment by Bobthe28th** [comment]
Ronan and Aidan say that hotbar selection is betta
