### ISSUE TITLE
New death message parameters

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#37]
Different death messages should show depending on:

Person who died or killed
Ex: Noah looked away from his battle cats to kill YourMom

Class
Ex: Owen killed Tristan, Wizard diff

It should also allow any death type to proc any other death message. For example, some death messages should also have the default death messages in their pool.

**Comment by Bobthe28th** [comment]
Also need to know what the new parameters actually should be
@Tman2143 any ideas?

**Comment by Bobthe28th** [comment]
@Tman2143 the reason I assigned you to this issue is that I want to know a list of parameters we should use, I gave some examples but idk what we should use in the final deathMessages.json

**Comment by Bobthe28th** [comment]
@Tman2143 bump

**Comment by Tman2143** [comment]
we should worry about this later if we even get to it
