### ISSUE TITLE
Demolitionist team damage/knockback 

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#38]
In the current state demolitionist does no knockback or damage to teammates, does half damage and massive knockback to self, and default damage and knockback to enemies.

Should the final version be like this?

**Comment by Tman2143** [comment]
demo should deal no damage to teammates and regular damage to enemies. it's kinda like junkrat's mines, used for mobility but also for getting kills and spacing. not sure exactly what to do with the rocket yet

**Comment by Tman2143** [comment]
also no knockback to teammates

**Comment by Bobthe28th** [comment]
> demo should deal no damage to teammates and regular damage to enemies. it's kinda like junkrat's mines, used for mobility but also for getting kills and spacing. not sure exactly what to do with the rocket yet

Also no knockback to teamates?

**Comment by Bobthe28th** [comment]
ok

**Comment by Bobthe28th** [comment]
It was already like that so... ok!
