### ISSUE TITLE
Flag on head when carrying 

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#39]
I think the classes all have unique helmets (only armor slot where we can use custom model data) but how do we want this to work with picking up the flag? Should the banner be in the helmet item slot? We cant have both at the same time.

**Comment by Bobthe28th** [comment]
Part of #14

**Comment by Bobthe28th** [comment]
I might be able to make an armorstand ride the player so it shouldn't lag behind (when carrying flag)

**Comment by Tman2143** [comment]
we'll see how things look in game before deciding what will be final

**Comment by Bobthe28th** [comment]
> we'll see how things look in game before deciding what will be final

Yea I have no idea if it will even work in the first place

**Comment by Bobthe28th** [comment]
![2022-01-27_18 13 01](https://user-images.githubusercontent.com/55060961/151475300-ccb0d578-deaa-4e9d-aa5e-8c5e8940c6dd.png)
offset is cringe and there is no real good way to fix it...
@Tman2143

**Comment by Tman2143** [comment]
just put it on their head

**Comment by Bobthe28th** [comment]
but then what about armor...

**Comment by Bobthe28th** [comment]
> I might be able to make an armorstand ride the player so it shouldn't lag behind (when carrying flag) Rotation may update slow tho

I did this
