### ISSUE TITLE
What should the maps be?

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#40]
Should there be a multiple map system?

Some things that I would like:
- [x] Medieval Castles
- [ ] Flat with a raised middle
- [x] Two mountains (idk)
- [ ] Farm
- [ ] Mining site (open, more like a quarry)
- [ ] That one map in tf2 with the powerups and grapple hook

**Comment by Bobthe28th** [comment]
And we also need people to actually work on it and not leave it to the last minute.
Gio seems good with map layout (although I didn't really like the mountain map)
Ella and Aidan are good with details
Ronan seems good with texture but his map design is weird (like the weird tunnel map he made)
I suck at all map things
Tristan and Aidan are good at map functionality and how the flow will actually work

**Comment by Bobthe28th** [comment]
Like they kinda need to start now

**Comment by Tman2143** [comment]
yea we should ask them about starting map concepts or building soon

**Comment by Bobthe28th** [comment]
> yea we should ask them about starting map concepts or building soon

I asked Aidan and he said maybe possible he could tomorrow

**Comment by Bobthe28th** [comment]
@Tman2143 we need to decide what maps we want to be made

**Comment by Tman2143** [comment]
we do

**Comment by Bobthe28th** [comment]
I meant it more like: what maps should be made?

**Comment by Bobthe28th** [comment]
@Tman2143

**Comment by Bobthe28th** [comment]
@Tman2143 bump

**Comment by Tman2143** [comment]
is this my job tho, the suggestions u out seem good and i can help make them if we need
