### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#46]
# We need da music
- Lobby
- Team Select
- Character Select
- Per map

Should music be individual (people can have different music on at the same time) or global?

**Comment by Bobthe28th** [comment]
in sounds.json set stream to true

**Comment by Tman2143** [comment]
https://www.youtube.com/watch?v=FfaEEYbWOf8
https://www.youtube.com/watch?v=TFAfyMc-W3w

**Comment by Bobthe28th** [comment]
@Tman2143 bump

**Comment by Tman2143** [comment]
those could be the only two tracks if we only have 1 map but if we have different maps then i can choose songs based of the maps theme
