### ISSUE TITLE
Need helmet models

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#56]
For all classes

- [x] Wizard (all sub classes)
- [x] Archer
- [x] Demolitionist
- [x] Paladin
- [x] Builder
- [x] Assassin
- [x] Alchemist

**Comment by Bobthe28th** [comment]
I have no idea what they should even be

**Comment by Tman2143** [comment]
wizard: wizard hat
archer: hood
demo: army looking helmet
paladin: helmet that kinda looks like hallow armor from terraria
builder: hard hat
assassin: darker hood than archer (maybe also shaped different)
alchemist: glasses and some frizzy hair if we can manage to do that

**Comment by Bobthe28th** [comment]
> alchemist: glasses and some frizzy hair if we can manage to do that

I would like for them to be 3d models so that would be very possible

**Comment by Tman2143** [comment]
yea i assumed they were gonna be 3d models it's more the artistic skill you need to make frizzy hair with voxels
