### ISSUE TITLE
Use Purpur instead of paper

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#58]
is better

**Comment by Bobthe28th** [comment]
Also max entity collisions to 2, ticks per monster 4, entity activation range (water, villager) 16, despawn ranges 28, arrow despawn 300, armor stands tick off blah blah, do timings report

**Comment by Bobthe28th** [comment]
\ue238

**Comment by Tman2143** [comment]
> Also max entity collisions to 2, ticks per monster 4, entity activation range (water, villager) 16, despawn ranges 28, arrow despawn 300, armor stands tick off blah blah, do timings report

what the hell does any of that even mean

**Comment by Bobthe28th** [comment]
cringe

**Comment by Bobthe28th** [comment]
https://purpurmc.org/

**Comment by Bobthe28th** [comment]
Doesn't really matter
