### ISSUE TITLE
Custom HUD with font (replaces cooldown timer)

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#59]
Using a custom font in the resource pack, I can replace unused unicode characters with custom images (something that indicated cooldown) and use actionbar title to display above the correct hotbar slot.

@Tman2143 Is it worth doing this?

**Comment by Bobthe28th** [comment]
or maybe its just random added work that is not important and I don't need to do

**Comment by Bobthe28th** [comment]
eh its not worth it

**Comment by Tman2143** [comment]
could be worth tho...?

**Comment by Tman2143** [comment]
hey google how to unclose on github

**Comment by Bobthe28th** [comment]
what would it look like tho

**Comment by Bobthe28th** [comment]
@Tman2143 bump

**Comment by Tman2143** [comment]
like a little bar kinda like the durability bard but a different color maybe light blue and it's above the item
