### ISSUE TITLE
Class attributes (health, armor, etc.)

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#61]
What should the health and armor of each class be?
Also enchantments

- Each half armor bar reduces damage by 4% for most damage types

**Comment by Tman2143** [comment]
demo man has feather falling

**Comment by Bobthe28th** [comment]
> demo man has feather falling

no shot

**Comment by Bobthe28th** [comment]
@Tman2143 bump

**Comment by Tman2143** [comment]
we need to work out damage and health after we finish all the classes

**Comment by Bobthe28th** [comment]
@Tman2143 we can actually do this now
