### ISSUE TITLE
Fire wizard book doesnt work, missing ability

### ISSUE THREAD

**Issue by Bobthe28th** [Bobthe28th/CaptureTheFart#92]
What even is the ability?

**Comment by Tman2143** [comment]
i had an idea but it's long gone in my memory

**Comment by Bobthe28th** [comment]
> i had an idea but it's long gone in my memory

He has the fire wall, then something that adds some sort of buff?

**Comment by Bobthe28th** [comment]
It's supposed to be some sort of "support" ability

**Comment by Tman2143** [comment]
yea i remember that but i just don't know what it was

**Comment by Tman2143** [comment]
i remember the fire wall

**Comment by Bobthe28th** [comment]
Maybe for the fire wall if we want it to not hurt allies, make fire particles be team color to differentiate
